### PR TITLE
0.0.1 Updates for the feature/gdal Branch

### PR DESCRIPTION
**Pull request by jbouffard**
This PR updates the `feature/gdal` branch so that it is in line with `master`.

### CODE REVIEW

**Comment by pomadchin** [comment]
@jbouffard your branch is already up to master

**Comment by pomadchin** [comment]
talking about https://github.com/geotrellis/geotrellis-contrib/pull/18
don't merge this PR

**Comment by jbouffard** [comment]
@pomadchin That's true. My main reason for wanting to merge this PR is so that it's easier to review #18 But if that won't bother you then I can remove this PR.

**Comment by jbouffard** [comment]
Closing this because #18 will merge in the changes as well.

**Pull request closed without merging**
