### PR TITLE
JPEG2000 Read Failure

### PR DESCRIPTION
**Pull request by metasim**
Includes random Sentinel 2 file. Error:

```
GDAL ERROR 0: 
geotrellis.gdal.GDALException: GDAL ERROR 0: 
	at geotrellis.gdal.GDALException$.lastError(GDAL.scala:36)
	at geotrellis.gdal.GDAL$.openPathDS(GDAL.scala:79)
	at geotrellis.gdal.GDAL$.openPath(GDAL.scala:75)
	at geotrellis.gdal.GDAL$.open(GDAL.scala:55)
	at geotrellis.gdal.GDAL$.fromGDALWarpOptions(GDAL.scala:99)
	at geotrellis.contrib.vlm.gdal.GDALBaseRasterSource$class.baseDataset(GDALBaseRasterSource.scala:48)
	at geotrellis.contrib.vlm.gdal.GDALRasterSource.baseDataset$lzycompute(GDALRasterSource.scala:23)
	at geotrellis.contrib.vlm.gdal.GDALRasterSource.baseDataset(GDALRasterSource.scala:23)
	at geotrellis.contrib.vlm.gdal.GDALBaseRasterSource$class.dataset(GDALBaseRasterSource.scala:50)
	at geotrellis.contrib.vlm.gdal.GDALRasterSource.dataset$lzycompute(GDALRasterSource.scala:23)
	at geotrellis.contrib.vlm.gdal.GDALRasterSource.dataset(GDALRasterSource.scala:23)
	at geotrellis.contrib.vlm.gdal.GDALBaseRasterSource$class.bandCount(GDALBaseRasterSource.scala:52)
	at geotrellis.contrib.vlm.gdal.GDALRasterSource.bandCount$lzycompute(GDALRasterSource.scala:23)
	at geotrellis.contrib.vlm.gdal.GDALRasterSource.bandCount(GDALRasterSource.scala:23)
	at geotrellis.contrib.vlm.gdal.GDALRasterSourceSpec$$anonfun$4$$anonfun$apply$mcV$sp$8.apply(GDALRasterSourceSpec.scala:168)
	at geotrellis.contrib.vlm.gdal.GDALRasterSourceSpec$$anonfun$4$$anonfun$apply$mcV$sp$8.apply(GDALRasterSourceSpec.scala:165)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
```

### CODE REVIEW

**Comment by pomadchin** [comment]
@metasim what's your `gdalinfo --formats | grep JP` ?

**Comment by metasim** [comment]
@pomadchin 

```
$ gdalinfo --formats | grep JP
  JPEG -raster- (rwv): JPEG JFIF
  JP2OpenJPEG -raster,vector- (rwv): JPEG-2000 driver based on OpenJPEG library
```

**Comment by metasim** [comment]
@pomadchin AAAK

I have two gdal installs:
```
$ /usr/local/opt/gdal2/bin/gdalinfo --formats  | grep JP
  JPEG -raster- (rwv): JPEG JFIF
```

Probably [EBCAK](https://www.urbandictionary.com/define.php?term=EBCAK). I'll followup.

**Comment by metasim** [comment]
Still have the error with 

    -Djava.library.path=/usr/local/opt/gdal2/lib

**Comment by pomadchin** [comment]
Not a bug, check it inside this container: `quay.io/azavea/openjdk-gdal:2.4-jdk8-slim`. You have a bad gdal installation.

**Comment by metasim** [comment]
Sorry!

**Comment by metasim** [comment]
For the archive, this fixes it:

```
brew install osgeo/osgeo4mac/osgeo-gdal
```

**Pull request closed without merging**
