### PR TITLE
Added integration test where GDAL reader takes longer than GeoTrellis reader

### PR DESCRIPTION
**Pull request by metasim**

### CODE REVIEW

**Comment by metasim** [comment]
Run with:

    sbt it:testOnly geotrellis.contrib.vlm.SubsceneReadingIT

**Comment by metasim** [comment]
@echeipesh @pomadchin Added another test for where GDAL is (significantly) slower than the `GeoTiffRasterSource`.

**Comment by pomadchin** [comment]
@metasim thanks will check em soon on a new setup

**Comment by pomadchin** [comment]
@metasim report using our own bindings; still not perfect: 

```
[info] Done compiling.
[info] SubsceneReadingIT:
[info] GDAL vs GeoTrellis GeoTiff reading
15:40:05 SubsceneReadingIT: Elapsed time of GeoTrellis is 2.5810s, producing ProjectedExtent(Extent(3440101.0175691093, -2315767.899836476, 3462532.0983280675, -2294035.527693799),EPSG:3857)
15:40:10 SubsceneReadingIT: Elapsed time of GDAL is 5.8370s, producing ProjectedExtent(Extent(3440101.0175691093, -2315767.899836476, 3462532.0983280675, -2294035.527693799),merc-CS)
[info] - should read projected extent with similar performance with GDAL *** FAILED *** (8 seconds, 615 milliseconds)
[info]   2581.0 was not 5837.0 plus or minus 1000.0 (SubsceneReadingIT.scala:56)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:346)
[info]   at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6668)
[info]   at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6704)
[info]   at geotrellis.contrib.vlm.SubsceneReadingIT$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(SubsceneReadingIT.scala:56)
[info]   at geotrellis.contrib.vlm.SubsceneReadingIT$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(SubsceneReadingIT.scala:42)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.FunSpecLike$$anon$1.apply(FunSpecLike.scala:454)
[info]   at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
[info]   at org.scalatest.FunSpec.withFixture(FunSpec.scala:1630)
[info]   at org.scalatest.FunSpecLike$class.invokeWithFixture$1(FunSpecLike.scala:451)
[info]   at org.scalatest.FunSpecLike$$anonfun$runTest$1.apply(FunSpecLike.scala:464)
[info]   at org.scalatest.FunSpecLike$$anonfun$runTest$1.apply(FunSpecLike.scala:464)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[info]   at org.scalatest.FunSpecLike$class.runTest(FunSpecLike.scala:464)
[info]   at org.scalatest.FunSpec.runTest(FunSpec.scala:1630)
[info]   at org.scalatest.FunSpecLike$$anonfun$runTests$1.apply(FunSpecLike.scala:497)
[info]   at org.scalatest.FunSpecLike$$anonfun$runTests$1.apply(FunSpecLike.scala:497)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
[info]   at scala.collection.immutable.List.foreach(List.scala:392)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
[info]   at scala.collection.immutable.List.foreach(List.scala:392)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
[info]   at org.scalatest.FunSpecLike$class.runTests(FunSpecLike.scala:497)
[info]   at org.scalatest.FunSpec.runTests(FunSpec.scala:1630)
[info]   at org.scalatest.Suite$class.run(Suite.scala:1147)
[info]   at org.scalatest.FunSpec.org$scalatest$FunSpecLike$$super$run(FunSpec.scala:1630)
[info]   at org.scalatest.FunSpecLike$$anonfun$run$1.apply(FunSpecLike.scala:501)
[info]   at org.scalatest.FunSpecLike$$anonfun$run$1.apply(FunSpecLike.scala:501)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
[info]   at org.scalatest.FunSpecLike$class.run(FunSpecLike.scala:501)
[info]   at org.scalatest.FunSpec.run(FunSpec.scala:1630)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
[info]   at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:304)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info]   at java.lang.Thread.run(Thread.java:748)
15:40:14 SubsceneReadingIT: Elapsed time of GeoTrellis is 3.4620s, producing Some(372620)
15:40:16 SubsceneReadingIT: Elapsed time of GDAL is 1.9440s, producing Some(372620)
[info] - should be faster reading subextent with GDAL (5 seconds, 409 milliseconds)
15:40:17 SubsceneReadingIT: reading 600 tiles
15:41:25 SubsceneReadingIT: Elapsed time of GeoTrellis is 68.6390s, producing 37194588
15:42:37 SubsceneReadingIT: Elapsed time of GDAL is 72.6380s, producing 37194588
[info] - should be faster reading full scene as tiles with GDAL *** FAILED *** (2 minutes, 21 seconds)
[info]   68639.0 was not greater than or equal to 72638.0 (SubsceneReadingIT.scala:90)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:346)
[info]   at org.scalatest.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6945)
[info]   at geotrellis.contrib.vlm.SubsceneReadingIT$$anonfun$1$$anonfun$apply$mcV$sp$3.apply(SubsceneReadingIT.scala:90)
[info]   at geotrellis.contrib.vlm.SubsceneReadingIT$$anonfun$1$$anonfun$apply$mcV$sp$3.apply(SubsceneReadingIT.scala:73)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.FunSpecLike$$anon$1.apply(FunSpecLike.scala:454)
[info]   at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
[info]   at org.scalatest.FunSpec.withFixture(FunSpec.scala:1630)
[info]   at org.scalatest.FunSpecLike$class.invokeWithFixture$1(FunSpecLike.scala:451)
[info]   at org.scalatest.FunSpecLike$$anonfun$runTest$1.apply(FunSpecLike.scala:464)
[info]   at org.scalatest.FunSpecLike$$anonfun$runTest$1.apply(FunSpecLike.scala:464)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[info]   at org.scalatest.FunSpecLike$class.runTest(FunSpecLike.scala:464)
[info]   at org.scalatest.FunSpec.runTest(FunSpec.scala:1630)
[info]   at org.scalatest.FunSpecLike$$anonfun$runTests$1.apply(FunSpecLike.scala:497)
[info]   at org.scalatest.FunSpecLike$$anonfun$runTests$1.apply(FunSpecLike.scala:497)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
[info]   at scala.collection.immutable.List.foreach(List.scala:392)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
[info]   at scala.collection.immutable.List.foreach(List.scala:392)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
[info]   at org.scalatest.FunSpecLike$class.runTests(FunSpecLike.scala:497)
[info]   at org.scalatest.FunSpec.runTests(FunSpec.scala:1630)
[info]   at org.scalatest.Suite$class.run(Suite.scala:1147)
[info]   at org.scalatest.FunSpec.org$scalatest$FunSpecLike$$super$run(FunSpec.scala:1630)
[info]   at org.scalatest.FunSpecLike$$anonfun$run$1.apply(FunSpecLike.scala:501)
[info]   at org.scalatest.FunSpecLike$$anonfun$run$1.apply(FunSpecLike.scala:501)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
[info]   at org.scalatest.FunSpecLike$class.run(FunSpecLike.scala:501)
[info]   at org.scalatest.FunSpec.run(FunSpec.scala:1630)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
[info]   at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:304)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info]   at java.lang.Thread.run(Thread.java:748)
15:43:33 SubsceneReadingIT: Elapsed time of GeoTrellis is 56.1430s, producing 37194588
15:43:33 SubsceneReadingIT: Elapsed time of GDAL is 0.0680s, producing 37194588
[info] - should be faster reading full scene GDAL (56 seconds, 217 milliseconds)
```

One thing here is that it takes a bit longer to read metadata (it is solvable if that would be a problem).
The second problem is that probably we're not doing efficient enough bands selection. But the results are comparable though ._. 

However there are some ways to improve it if that would be the case.

Will merge your tests into our new bindings branch.

@jamesmcclain ^

**Comment by pomadchin** [comment]
@metasim can you check other backends; like S3? It can be a backend specific thing also; since GDAL has it's own ways to optimize and cache things.

**Comment by jamesmcclain** [comment]
> Will merge your tests into our new bindings branch.

:+1:

**Comment by jamesmcclain** [comment]
Actually, I am not sure if it makes sense to merge anything into that branch ... it has a number of conflicts now: https://github.com/geotrellis/geotrellis-contrib/pull/130

**Comment by pomadchin** [comment]
Will follow @jamesmcclain advise, merging it into the current master. It's good to keep such things in our actual branch.

**Comment by metasim** [comment]
@pomadchin @echeipesh FYI, reading metadata quickly is *extremely* important to us. The main point of RF RasterRefs is to enable us to reason spatially about the tiles before actually reading them, and to do that we currently read just the header with the original GeoTiff reader. So when I say "metadata" I really mean standard GeoTIFF header stuff, not extended things like the XML sidecar files, etc.

**Comment by metasim** [comment]
@pomadchin When you say to "try with S3", do you mean using the `GDALRasterSource` or the `GeoTiffRasterSource`? Technically they'd both work, I think.

**Comment by pomadchin** [comment]
@metasim i meant both, right. You can just throw me an S3 URI to the same tiffs to test. Or I can put em in our buckets.

**Comment by pomadchin** [comment]
Tbh I don't think that HTTP(s) protocol is at all widely used somewhere ._. but I suppose in some RF cases it's used.

**Comment by metasim** [comment]
We use HTTP(s) quite a alot :( Maybe ill-advisedly? But out of convenience....

**Comment by pomadchin** [comment]
@metasim oops! okay I think i just didn't know about it :D niice

**Comment by metasim** [comment]
@pomadchin Here's the S3 URL version:

s3://radiant-nasa-iserv/2014/02/14/IP0201402141023382027S03100E/IP0201402141023382027S03100E-COG.tif

**Comment by pomadchin** [comment]
@metasim gotcha will check it out. I plan to update today / tomorrow things in a master branch to use new bindings, after that will create a bunch of performance related issues. That's the plan.

If you have any other _test_ ideas, you're welcome to push as much as you can! It's pretty useful. But I'd say that everything is possible. 

Our main use case of these bindings was RF, so we could beat a GeoTrellis Java Reader even without having caching for tiles enabled.

However James will push things froward with bindings if that would be required (and it looks like it would be required soon). 

Also I think you're welcome to improve performance yourself: https://github.com/geotrellis/gdal-warp-bindings

**Comment by metasim** [comment]
@pomadchin I wish I could jump in and help with the bindings (would be fun), but I'm barely keeping my head above water 🌊 I'm in a "make do with what you've got" mode. :-)

**Pull request merged**
